FROM python:3.11.9-slim

WORKDIR /messenger

# Копируем зависимости
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект, включая main.py в корне
COPY . .

EXPOSE 8000

# Запуск main.py с uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
